---
version: "3.9"

services:
  devopsdb:
    image: pramodcg32/img:db
    ports:
      - "3306:3306"

  application:
    image: pramodcg32/img:app
    ports:
      - "2222:8080"
    depends_on:
      - devopsdb
