version: "3"

services:
  devopsdb:
    image: pramodcg32/img:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 2
    networks:
      - mynetwork

  application:
    image: pramodcg32/img:app
    ports:
      - "3333:8080"
    deploy:
      replicas: 2
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
